language: node_js
node_js:
- '0.11'
- '0.10'
deploy:
  provider: npm
  email: sqrt@octoblu.com
  api_key:
    secure: hgyXcGJUVMJRo2QmykVCxzdMLNlFx0viEhQyF6kgBiQCtPp+zspmm1cPzrEV0mSIi/O/7EsweAK2oDfLlbWn/kCgKsa5j3Fb/zSvtyXzmT5vg8BfErjadWnA7JkRkzyXDrvgoaI/wZIncz2F3/3RDXoUfuAMXwC9DmBVzhHJNXkeCw1aE4xh6AJhTxsH6nSIBKQcGaLh6IIeKuiSWo6i9u6c03YJSAvG2kXu6s9mxuVOWu0mD0dJe5IRPFmrH26MmNlhpUPK/S/BdcrpR3+bbQreKoQ42/S6xZhgYbJtvHC4BrV0YfUtS3sHsd0d1M5lkw0BwhQ8BWOOtdIwG3Ac+NUnfooanRRLTEAkrlZNicIMGBLb42uScAv06NklBUVpfOkakDxM5gWc6KCGBzN2eTq73noHwAilLOhXQVLM1qQ0kpparImoqjUVk/0NqKrLMlNIzsWYRSZzm7kVGBnos0U9Ug9RUiERFZZ63eIyyXPn4znNnj5Kir9JaTEr8KydznPIueto+kVwD8quec0eOKtdziOXBrrcJpAtiADhOjs7is62UR1AtxU6bDF7uzclawf+6i/q5qzOJMH7YW+9Pt3v0S4hN/oLNLcFOU5Us3WhHvIN135IOPBSHOEUGAiIhvaHeCGVTscGbcIqmL5IhntwJsvp8Yske1nHGXlk04o=
  on:
    tags: true
    repo: octoblu/nanocyte-node-equal
